apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: other-api
  name: other-api
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: other-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: other-api
    spec:
      containers:
        - image: kevcoxe/test-kubernetes-other-api:0.0.8
          imagePullPolicy: Always
          name: other-api
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: other-api
  name: other-api
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: other-api
  sessionAffinity: None
  type: NodePort
