apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-frontend
    version: v7
  name: test-frontend
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: test-frontend
      version: v7
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-frontend
        version: v7
    spec:
      containers:
        - image: kevcoxe/test-kubernetes-frontend:0.0.7
          imagePullPolicy: Always
          name: test-frontend
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-frontend
  name: test-frontend
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: test-frontend
    version: v7
  sessionAffinity: None
  type: LoadBalancer