apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-frontend
  name: test-frontend
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: test-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-frontend
    spec:
      containers:
        - image: kevcoxe/test-kubernetes-frontend:0.0.10
          imagePullPolicy: Always
          name: test-frontend
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-frontend
  name: test-frontend
  namespace: default
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: test-frontend
  sessionAffinity: None
  type: NodePort
