version: "3.7"

services:
  flask_api:
    build: ./backend/flask-api
    container_name: flask-api
    restart: always
    environment:
      - APP_NAME=FlaskApi
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - "8000:8000"
