version: "3.7"

services:
  # local build of the flask api
  flask-api-local:
    build: ./backend/flask-api
    container_name: flask-api
    restart: always
    environment:
      APP_NAME: FlaskApi
      API_VERSION: 0.0.4
      HOST: 0.0.0.0
      PORT: 8000
    expose:
      - 8000

  # local build of the nginx and react frontend
  nginx-react-local:
    build: ./frontend
    container_name: nginx-react
    restart: always
    ports:
      - "80:80"
