apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-api
  name: flask-api
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: flask-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - image: kevcoxe/test-kubernetes-flask-api:0.0.6
          imagePullPolicy: Always
          name: flask-api
          ports:
          - name: liveness-port
            containerPort: 5000
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          readinessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-api
  name: flask-api
  namespace: default
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: flask-api
  sessionAffinity: None
  type: NodePort
